---
- name: Test Playbook...
  hosts: localhost
  become: yes
  gather_facts: no
  vars:
    user: sunday
    packagelist:
      - curl
      - wget
      - acl
      - git
      - zsh
      - vim
      - direnv 
      - tmux
      - emacs
      - ranger
  roles:
    - role: dotfiles
