---
- name: Test Playbook...
  hosts: localhost
  become: yes
  gather_facts: no
  vars:
    sudogroup: admin
    user: sunday
    publickeyfile: /vagrant/key/sunday.pub
    hostfile: /vagrant/config/hosts.github
    packagelist:
      - git
      - zsh
      - vim
      - curl
      - wget
      - tmux
  roles:
    - role: user
    - role: host
    - role: package
    - role: dotfiles
